---
  - name: PHP5-FPM | Add repository for PHP 5.4
    sudo: yes
    apt_repository: repo='ppa:ondrej/php5-oldstable' state=present update_cache=yes

  - name: PHP5-FPM | install php5-fpm
    sudo: yes
    action: apt name={{ item }} state=latest
    with_items:
      - php5-fpm
      - php5-cli
    notify:
      - restart php5-fpm

  - name: PHP5-FPM | Install composer
    sudo: yes
    shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
