---
  - name: Install Nginx if not available
    sudo: yes
    apt: pkg=nginx
    notify:
      - restart nginx

  - name: update the default site configuration
    sudo: yes
    template: src=default.site.j2 dest={{nginx_dir}}/sites-available/default owner=root group=root mode=0644
    notify:
      - restart nginx

  - name: enable the default site
    sudo: yes
    file: path={{nginx_dir}}/sites-enabled/default src={{nginx_dir}}/sites-available/default state=link
    notify:
      - restart nginx
